tex:
	pandoc chap1.md --listings -o chap1.tex
	pandoc chap2.md --listings -o chap2.tex
	pandoc chap3.md --listings -o chap3.tex
	pandoc chap4.md --listings -o chap4.tex
	pandoc chap5.md --listings -o chap5.tex
	pandoc chap6.md --listings -o chap6.tex

all: tex
	pdflatex main < /dev/null
        # detect if pdfsizeopt is present
        # gives 48% lossless compression on our submission
	# disabled as it breaks pdfs generated by gnuplot. Curious why?
	# (command -v pdfsizeopt >/dev/null 2>&1 && { mv paper.pdf paper-big.pdf; pdfsizeopt paper-big.pdf paper.pdf; }) || true

cheat:
	pandoc cheat-content.md --listings -o cheat-content.tex
	pdflatex cheat < /dev/null

work:
	ls *.md main.tex | entr make all # work with skim for auto refresh

clean:
	rubber -d --clean main
